blank_issues_enabled: true
contact_links:
  - name: Bug Report
    url:
  - name: Community Support
    url: https://github.com/textlint-rule/sentence-splitter/discussions
    about: Please ask and answer questions here.
